apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  generation: 1
  name: edge-gateway
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 80
      protocol: HTTP
