{{- if eq .Values.backend.type "external" }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: {{ .Values.service.name }}-backend
  namespace: {{ .Values.service.namespace }}
spec:
  endpoints:
    - fqdn:
        hostname: {{ .Values.backend.external.host }}
        port: {{ .Values.backend.external.port }} 
{{- end }}