{{- if .Values.timeouts.enabled }}

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy

metadata:
  name: {{ include "edge-service.policyName" . }}
  namespace: {{ .Values.service.namespace }}

spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "edge-service.fullname" . }}

  timeout:
    http:
      requestTimeout: {{ .Values.timeouts.request }}

{{- end }}