apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway-metrics
  namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/name: envoy
    app.kubernetes.io/component: metrics
spec:
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway-dev
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: edge-gateway-dev
    gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
  ports:
    - name: metrics
      port: 19001
      targetPort: 19001
      protocol: TCP
