apiVersion: v2
name: envoy-gateway-bootstrap
version: 1.0.0

dependencies:
  - name: gateway-helm
    version: "v1.8.3"
    # Change from oci://docker.io/... to registry-1.docker.io
    repository: "oci://registry-1.docker.io/envoyproxy"
