gatewayClass:
  name: eg
  controllerName: gateway.envoyproxy.io/gatewayclass-controller

gateway-helm:
  config:
    envoyGateway:
      provider:
        type: Kubernetes
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      extensionApis:
        enableBackend: true
