gatewayClass:
  name: eg
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: eg

envoyProxy:
  name: eg
  service:
    type: ClusterIP

gateway-helm:
  config:
    envoyGateway:
      provider:
        type: Kubernetes
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      extensionApis:
        enableBackend: true
