apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-backend
  namespace: argocd
spec:
  project: edge-gateway
  source:
    repoURL: https://github.com/llauderesv/edge-gateway.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
      include: '{external-backend}/*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true