apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edge-gateway
  namespace: argocd
spec:
  description: Enterprise Edge Gateway
  sourceRepos:
    # - https://github.com/llauderesv/edge-gateway.git
    # - oci://docker.io/envoyproxy
    - '*'
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
    ignore:
      - group: argoproj.io
        kind: Application