gatewayClass:
  name: eg
  controllerName: gateway.envoyproxy.io/gatewayclass-controller

envoyProxy:
  name: eg
  service:
    type: ClusterIP
  replicas: 2

# gateway-helm:
#   config:
#     envoyGateway:
#       provider:
#         type: Kubernetes
#       gateway:
#         controllerName: gateway.envoyproxy.io/gatewayclass-controller
#       extensionApis:
#         enableBackend: true
