apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envoy-data-plane
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - environment: dev
            listeners:
              - name: http
                port: 80
                protocol: HTTP
              - name: https
                port: 443
                protocol: HTTPS
                hostname: localhost
                tlsSecret: dev-localhost-tls
          - environment: qa
            listeners:
              - name: https
                port: 443
                protocol: HTTPS
                hostname: localhost
                tlsSecret: dev-localhost-tls
          - environment: prod
            listeners:
              - name: https
                port: 443
                protocol: HTTPS
                hostname: localhost
                tlsSecret: dev-localhost-tls
  template:
    metadata:
      name: envoy-data-plane-{{ .environment }}
    spec:
      project: edge-gateway
      source:
        repoURL: https://github.com/llauderesv/edge-gateway.git
        targetRevision: HEAD
        path: charts/envoy-data-plane
        helm:
          values: |
            gateway:
              name: envoy-data-plane-{{ .environment }}
              namespace: envoy-gateway-system
              gatewayClassName: eg
              allowedRoutes:
                namespaces:
                  from: All
              listeners:{{ range .listeners }}
                - name: {{ .name }}
                  port: {{ .port }}
                  protocol: {{ .protocol }}
                  {{ if .hostname }}
                  hostname: {{ .hostname | quote }}
                  {{ end }}
                  {{ if .tlsSecret }}
                  tls:
                    mode: Terminate
                    certificateRefs:
                      - kind: Secret
                        name: {{ .tlsSecret }}
                  {{ end }}
              {{ end }}
            envoyProxy:
              name: eg-{{ .environment }}
              service:
                type: ClusterIP
              replicas: 2
      destination:
        server: https://kubernetes.default.svc
        namespace: envoy-gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
