apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: edge-gateway
  source:
    chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.8.3
    helm:
      values: |
        config:
          envoyGateway:
            extensionApis:
              enableBackend: true
          provider:
            type: Kubernetes
            kubernetes:
              deploy:
                type: GatewayNamespace # 👈 This shifts data-plane ownership down to the local Gateway
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true