apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-dev
  namespace: argocd
spec:
  project: edge-gateway
  source:
    repoURL: https://github.com/llauderesv/edge-gateway.git
    targetRevision: HEAD
    path: charts/edge-gateway
    helm:
      valueFiles:
        - ../../clusters/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
